# Generated by Django 4.1 on 2023-01-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_room_delete_account"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
    ]
