# Generated by Django 4.1 on 2023-01-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0002_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
