# Generated by Django 4.1 on 2023-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0007_message_when"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="when",
            field=models.CharField(max_length=1000),
        ),
    ]
